export interface LoginRequest{
  email: string,
  password: string
}


export interface RegisterRequest{
  name:     Name;
  email:    string;
  password?: string;
  role:     string;
  image:    string;
}

export interface Name {
  first: string;
  last:  string;
}

// Generated by https://quicktype.io

export interface User {
  _id:      string;
  name:     Name;
  email:    string;
  password: string;
  image:    string;
  role:     string;
  __v:      number;
}

export interface Name {
  first: string;
  last:  string;
}

